# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1cfb9e82e4e272528a8d9c6f465d7080d6641a778c3910515c4702ff532363e0ec188784b90938319be780e99bc96cacb02fd5bc8e8f8b98a72619adc36272b

test:
  secret_key_base: aad59b4cac27e2b60ad61c7186312a7500cac42cffb4e14d2839c03a615994bc2430f8432ce9da347c3a13904ca179e76726ff28fe3b75ead812952be1caeab2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
